spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:hsqldb:mem:restaurantvote
    username: sa
    password:

  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

logging:
  level:
    root: WARN
    com.github.maxsouldrake.restaurantvote: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.security: DEBUG

server.servlet:
  register-default-servlet: true
  encoding:
    charset: UTF-8
    enabled: true
    force: true